networks:
  my_custom_network:
    name: my_custom_network
    driver: bridge

services:
  java-app:
    build: .
    environment:
      BASE_ATTRACTION_URL: http://attraction-service:8080/api/attractions
      BASE_S3_URL: http://storage-service:8080/files/
    ports:
      - "5300:8080"
    networks:
      - my_custom_network